main: me.woutergritter.hueambiance.HueAmbiance
name: hue-ambiance
version: 0.1
api-version: 1.19
commands:
  hueconnect:
    description: 'Connect to the Hue bridge.'
  hueenable:
    description: 'Enable or disable Hue ambiance for yourself.'
  hueroom:
    description: 'View or edit the Hue room connected to yourself.'
